### ISSUE TITLE
Can't navigate to specific component from 'All Components' page

### ISSUE THREAD

**Issue by joshfarrant** [blueberryapps/react-bluekit#103]
**Steps to reproduce**

1. Start in 'All components' view.
2. Click on link to a specific component
3. Note the error in the console.

The error I'm seeing is as follows:

`Uncaught TypeError: BluekitEvent is not a constructor`

which comes from [this line](https://github.com/blueberryapps/react-bluekit/blob/2671ca8a6337697840c3363618fc30787df80aae/nunjucks/componentsIndex.nunjucks#L9).

Running latest version from npm (`0.4.0-typescript05`)

Let me know if you'd like any more info :+1:

**Comment by ondrejbartas** [comment]
Pls try to use 0.4.0 version without -typescript

We are still working on that version

**Comment by joshfarrant** [comment]
Ok no problem - It doesn't appear that 0.4.0 without Typescript was ever published to npm

```
npm ERR! notarget 0.4.0-typescript05, 0.4.0-typescript04, 0.4.0-typescript03, 0.4.0-typescript02, 0.4.0-typescript01, 0.4.0-typescript, 0.3.2, 0.3.1, 0.3.0, 0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.15, 0.1.14, 0.1.13, 0.1.12, 0.1.11, 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.3-cli, 0.1.2, 0.1.1, 0.1.0, 0.0.31, 0.0.30, 0.0.29, 0.0.28, 0.0.27, 0.0.26, 0.0.25, 0.0.24, 0.0.23, 0.0.22, 0.0.21, 0.0.20, 0.0.19, 0.0.18, 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.13
```

I'll switch back to 0.3.2 and close this for now anyway.
