### ISSUE TITLE
PropTypes in React 15.5 Support

### ISSUE THREAD

**Issue by lord-xeon** [blueberryapps/react-bluekit#116]
In React v 15.5.0, Facebook extracted PropTypes from the base React scope and placed them into their own package - `prop-types`

Upon changing my code to support the new loading, Bluekit is showing every property as "custom"

**Comment by ondrejbartas** [comment]
Shoul be fixed by #113.

I just released version 0.4.3 whoch contains that fix

**Comment by lord-xeon** [comment]
That fixes it thanks!
