### ISSUE TITLE
IE11: Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by davidcalhoun** [blueberryapps/react-bluekit#130]
Getting this error when running the demo page with Internet Explorer 11 (demo page: http://bluekit.blueberry.io/demo).  Click on any element in the sidebar to reproduce what you can see below:

![screen shot 2017-11-28 at 3 06 25 pm](https://user-images.githubusercontent.com/120596/33349519-4c748d54-d44f-11e7-8c53-45f7741563be.png)

It's pointing to this line of code: https://github.com/blueberryapps/react-bluekit/blob/c81e3af66caa3a634082c67da21f197a8d8f6f3e/src/app/component/PropsSidebar.react.js#L157

On the demo site my debugger claims both `area` and `pickerButton` are undefined, but in the app I'm developing on my own, both of these are defined, and `pickerButton` seems to be an SVG element, which may be the trouble.  IE has supported `Node.prototype.contains` since IE 5: https://developer.mozilla.org/en-US/docs/Web/API/Node/contains#Browser_compatibility

Thanks in advance!

EDIT: Looks like it is related to `pickerButton` being an SVGElement.  You can try this in your console on IE11 (while running the demo page linked to above): `document.querySelector('svg').contains`, which returns `undefined`.  Try the same in Chrome and it returns the native `contains` function.

**Comment by imtoo** [comment]
Hi, we do not support IE since it's not officially supported by Microsoft https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support

We recommend using different browser than IE.

**Comment by davidcalhoun** [comment]
Thanks for the quick reply.  No worries, but it would be handy to have a disclaimer in the readme somewhere.  Some folks still have users running on IE11 (out of our control), and it would be handy for them to see browser support right on the readme, so they can better evaluate whether to use BlueKit.

Thanks!
