### ISSUE TITLE
Add the ability to exclude files/folders from the build

### ISSUE THREAD

**Issue by andrefox333** [blueberryapps/react-bluekit#71]
Another minor request :)

It would be nice to have the ability to exclude files/folders when I run Bluekit. Kind of like how you're automatically excluding `__test__` but maybe make that more configurable on a Gulp task level. 

Thank you!

**Comment by imtoo** [comment]
Yes, that makes sense. I added it to To-do list in our board and we'll look on it probably in next sprint.

You can also make PR if you'd like it ealier.

Many thanks!

**Comment by joshfarrant** [comment]
Any thoughts on a rough time-frame for this one guys?

**Comment by imtoo** [comment]
We thought that it'd be earlier but then we got other priorities. Probably in 1-2 weeks.

**Comment by joshfarrant** [comment]
Great, thanks for getting back to me. Look forward to trying it out.

**Comment by imtoo** [comment]
Added in #99
