### ISSUE TITLE
Make compatible with flowtype

### ISSUE THREAD

**Issue by naturalethic** [blueberryapps/react-bluekit#80]
Adding flowtype notations to a component breaks bluekit compilation.

**Comment by naturalethic** [comment]
More specifically, using flowtype types on component props breaks the buildProps function.

**Comment by imtoo** [comment]
Hi, can you send us link or code of your component that breaks the build? Thanks.

**Comment by naturalethic** [comment]
The primary issue is that flowtype types are reported with a different property name than PropType types.  We've decided to not use flowtype for now, due to this and other incompatibilities, but a quick hack demonstrated in the following commit got it to compile properly.

https://github.com/naturalethic/react-bluekit/commit/69cf095b2b4218437a02add8fbd5ea4cba4346c2

**Comment by imtoo** [comment]
Good point! I've created PR #90. Thanks for the feedback and commit! It will be in upcoming release.

**Comment by kjg531** [comment]
Is this confirmed working? I tried to switch out one of the examples proptypes for flowtypes and it doesn't seem to pick anything up.

**Comment by imtoo** [comment]
Yea, it was working when we tried it. It's part of v0.3.1 release. Here's parser doc https://github.com/reactjs/react-docgen#flow-type-support

**Comment by kjg531** [comment]
Does anyone have a working example component working?
