### ISSUE TITLE
watch-bluekit only looks for .js files, not .jsx

### ISSUE THREAD

**Issue by OscarBarrett** [blueberryapps/react-bluekit#83]
At [src/createBlueKit.js#L115](https://github.com/blueberryapps/react-bluekit/blob/eda6418c0b394e7babce902bad0f2f9536f6ce67/src/createBlueKit.js#L115)

Whereas the build-bluekit task uses `getAllFilesInDir` which matches on `/\.(js|jsx)$/` ([src/createBlueKit.js#L26](https://github.com/blueberryapps/react-bluekit/blob/eda6418c0b394e7babce902bad0f2f9536f6ce67/src/createBlueKit.js#L26)).

**Comment by imtoo** [comment]
Thanks.
