### ISSUE TITLE
Add ability to annotate a component and have that comment display in interface as notes

### ISSUE THREAD

**Issue by joshfarrant** [blueberryapps/react-bluekit#93]
I believe it would be useful to display a 'notes' section in the component interface which can be used to add relevant component usage notes to clarify details about component usage.

For example; let's say I write a simple _Button_ component that takes an optional `href` prop which, if supplied, will render the same button as an `<a>` tag with the given `href`, rather than as a `<button>`. This information isn't immediately obvious to a new user looking at the list of props for this component for the first time. Currently information like this would have to be included in the project README, which is fine, but means the user needs to check elsewhere to find out all of the relevant information. I think there's room in BlueKit for this information.

I'd imagine this would be implemented so that we could annotate the component file with a comment, perhaps in a standardised format, which would then be displayed as notes alongside the component props in BlueKit.

Maybe something like...

```
import React, { PropTypes, Component } from 'react';

/** bluekit:notes
 * Button takes an optional 'href' prop which, if supplied, renders
 * an <a> tag, rather than a <button>.
 */

class Button extends Component {

// ...

```

![image](https://cloud.githubusercontent.com/assets/6840861/20751241/a74e3386-b6f2-11e6-8bc2-565def2ceccc.png)

What do you guys think about this?

**Comment by imtoo** [comment]
Hi, I've made a quick PR #94 that should solve your problem. It has to be written in accordance with https://github.com/reactjs/react-docgen

Thanks for the feedback.
