### ISSUE TITLE
Cannot collapse a folder

### ISSUE THREAD

**Issue by patricksmith** [blueberryapps/react-bluekit#97]
Attempting to collapse a folder in the nav tree on the left causes an error in the console:

![image](https://cloud.githubusercontent.com/assets/1062277/22352840/cfed3262-e3eb-11e6-9dc8-bda40e9fd165.png)

I think this is because `react-bluekit` [requires `immutable>=3`](https://github.com/blueberryapps/react-bluekit/blob/5229ee8e4c0222d052488850f04a2f1c79e0dbe9/package.json#L77) while it appears the `keyOf` method was [added for Lists in v3.8.1](https://github.com/facebook/immutable-js/releases/tag/v3.8.1). (I'm seeing this error with `immutable` version 3.7.6)

**Comment by imtoo** [comment]
Resolved. Thanks for the report.
